spring:
  config:
    activate:
      on-profile: test
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://test-rds.c35pvkgak4n8.ap-northeast-2.rds.amazonaws.com:3306/creadible?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: h13001212!
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  batch:
    jdbc:
      initialize-schema: always